In [1]:
# importando as bibliotecas

import numpy as np
import cv2

In [2]:
# carregando a imagem a ser analisada

img = cv2.imread('CV_Lista02_dados/goi1.jpg', 0)

In [3]:
# calculando as derivadas da imagem
Wd = 3

dx = cv2.Sobel(img, -1, 1, 0, ksize=Wd)
dy = cv2.Sobel(img, -1, 0, 1, ksize=Wd)

In [4]:
dxdx = dx ** 2
dydy = dy ** 2
dxdy = dx * dy

In [15]:
# definindo os elementos da matriz de correlacao para cada pixel
width = img.shape[0]
heigh = img.shape[1]
offset = int(((5 * Wd) - 1) / 2)
threshold = 5000

corner = np.zeros((width, heigh))

np.pad(dxdx, ((offset, offset), (offset, offset)), 'constant')
np.pad(dydy, ((offset, offset), (offset, offset)), 'constant')
np.pad(dxdy, ((offset, offset), (offset, offset)), 'constant')

for y in range(heigh):
    for x in range(width):
        pixel_dxdx = dxdx[x * offset : (x + 2) * offset + 1, y * offset : (y + 2) * offset + 1]
        pixel_dydy = dydy[x * offset : (x + 2) * offset + 1, y * offset : (y + 2) * offset + 1]
        pixel_dxdy = dxdy[x * offset : (x + 2) * offset + 1, y * offset : (y + 2) * offset + 1]
        
        m = [[pixel_dxdx, pixel_dxdy], [pixel_dxdy, pixel_dydy]]
        
        lamb1 = np.linalg.eig(m)[0][0]
        lamb2 = np.linalg.eig(m)[0][1]
        
        print(lamb1)
        print(lamb2)
        
        R = lamb1 * lamb2 - 0.04 * (lamb1 + lamb2) ** 2
        
        if R > threshold:
            corner[x, y] += R

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()